### ISSUE TITLE
Test set 

### ISSUE THREAD

**Issue by robbyneven** [johnsk95/PT4AL#1]
Hi, after every training epoch you test your model on a test set. Why do you load the full 50k training images and not the 10k test images?

**Comment by johnsk95** [comment]
Hello, 
This is intended for two reasons:
1. Prevent the pretext task model from learning the distribution of the test set, since the test set is used in the active learning phase. 
2. To better fit the pretest task model to the unlabeled data. 
Hope this helps!

**Comment by robbyneven** [comment]
I understand that you use the train set for training and testing the pretext task. But in your main script, in the active learning phase, the test set is an instance of the Loader2 class with the "is_train" switch set to 1, which loads the train set (line 58 in loader.py).
