### ISSUE TITLE
Your code use trainset for test phase ?

### ISSUE THREAD

**Issue by quannguyen268** [johnsk95/PT4AL#10]
![image](https://user-images.githubusercontent.com/79714533/208338501-cf1eb33d-f500-4ced-aefd-c0551671b710.png)
![image](https://user-images.githubusercontent.com/79714533/208339808-b9fdd543-3dbe-4db4-9753-35c16d44c4b5.png)

In main.py, your testset look like above: is_train=False, path=None. So, self.img_path in Loader2 will take data from glob.glob('./DATA/train/*/*'). Which means, you are using traindataset for testing ?

**Comment by seominseok0429** [comment]
There was a mistake. The code where there was an error has been corrected. 

thank you
