### ISSUE TITLE
Where can I download './DATA/train/*/*' ?

### ISSUE THREAD

**Issue by lijiaoyang** [johnsk95/PT4AL#3]
thanks

**Comment by ia-gu** [comment]
hi, 
did you solve the problem?
I'm facing the same thing and I wanna know what to do.
Thanks in advance

**Comment by johnsk95** [comment]
The files in DATA are the images directly downloaded from the CIFAR10 dataset.

**Comment by ia-gu** [comment]
I've already downloaded CIFAR10 on './DATA', but I got an error message 'num_samples should be a positive integer value, but got num_samples=0' when I try to run 'rotation.py'
Is there any other possible reason?
