### ISSUE TITLE
About Test Dataset

### ISSUE THREAD

**Issue by ia-gu** [johnsk95/PT4AL#4]
Hi, 
I have a question about test in "main.py".

As I read your code, you use TRAIN dataset for test section(in main.py, line 44, 45)
Is there any reasons why you've done that?

thanks a lot in advance.

**Comment by johnsk95** [comment]
`testset = Loader2(is_train=False,  transform=transform_test)`

If you are referring to this line, we are using the test dataset for the testset.

**Comment by ia-gu** [comment]
However, you don't give path_list and then Loader2 return data in ('./DATA/train/*/*').
There is no path for ('./DATA/test/*/*') in Loader2, isn't it?

**Comment by seominseok0429** [comment]
> However, you don't give path_list and then Loader2 return data in ('./DATA/train/_/_'). There is no path for ('./DATA/test/_/_') in Loader2, isn't it?

```
import torch
import torchvision
from PIL import Image

class save_dataset(torch.utils.data.Dataset):

  def __init__(self, dataset):
    self.dataset = dataset

  def __getitem__(self, i):
      x, y = self.dataset[i]
      path = './DATA/test/'+str(y)+'/'+str(i)+'.png'
      x.save(path)


  def __len__(self):
    return len(self.dataset)

trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=None)
#trainloader = torch.utils.data.DataLoader(trainset, batch_size=128, shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=None)
#testloader = torch.utils.data.DataLoader(testset, batch_size=100, shuffle=False, num_workers=2)

dataset = save_dataset(testset)

for a, i in enumerate(dataset):
    dataset[a]
```
Save the data with the above code

**Comment by ia-gu** [comment]
@seominseok0429 Thanks, but I've already modify the code by myself.
I wanna know wether the authors used the original code  on experiments for thesis they prposed.

**Comment by johnsk95** [comment]
Hello, 
Yes, we used the exact code in this repository to produce the results in the paper.

**Comment by ia-gu** [comment]
I got it, 
thanks for answering
