### ISSUE TITLE
Training Sorted batches for AL cycle 

### ISSUE THREAD

**Issue by manza-ari** [johnsk95/PT4AL#7]
Hi, thank you so much for your sharing your work. 

So I wanted to ask one thing once we are done with the pretext task and sorting with batches,  we will train for an active learning cycle from scratch? 

There is no information from the previous training to the next training which is Active Learning training. Am I getting correct?

**Comment by johnsk95** [comment]
Yes the active learning task is trained from scratch. 
Unlike transfer learning, the pretext task learning and active learning cycles are separate.
